title: Saurav Kumar # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced data strategist transitioning to a Data Scientist role. Proficient in statistical analysis, data visualization, machine learning, and NLP with Python, Docker, and Tableau. 
  <br><br>
  <a href="https://www.linkedin.com/in/arsauravkr/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://arsauravkr.github.io/resume/">View My Resume</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
